---
title: "Email Testing"
author: "Collin Henley"
date: "August 27, 2019"
output: pdf_document
---


```{r}

library("mailR")
```



```{r}

send.mail(from = "better.business.apps@gmail.com",
          to = c("chenley4@gmu.edu"),
          #replyTo = c("Reply to someone else <someone.else@gmail.com>"),
          subject = "Testing in R",
          body = "Testing this out",
          smtp = list(host.name = "smtp.gmail.com", port = 465, user.name = "better.business.apps", passwd = "BetterB12000", ssl = TRUE),
          authenticate = TRUE,
          send = TRUE,
          debug = TRUE)



```



```{r}
for (i in 1:length(5)) {
  
  
  subject <- "Hello"
  msg <- "Nothing"
  sender <- "collinhenley24@gmail.com"
  recipients <- "collinhenley24@gmail.com"
  # path <- parseFilePaths(volumes, input$file)
  # fileName <-   shinyDirChoose(input, 'dir', roots = c(home = '~'), filetypes = c('pdf', 'html'))
  send.mail(from = sender,
            to = recipients,
            subject = subject,
            body = msg,
            #body,
            #attach.files = path$datapath,#file.path(folder, fileName),
            # attach.files = path$datapath,
            # attach.files  = c("./my-report.pdf"),
            #file.names = c("Download my-report.pdf"),
            # file.names = path$name,
            smtp = list(host.name = "smtp.gmail.com", port = 465,
                        user.name=sender, passwd="Bumpass2041170!", ssl=TRUE),
            authenticate = TRUE,
            send = TRUE)
  
}

```




attempting to do this with the package gmailr
```{r}
# library gmailr
library(gmailr)

# JSON creditentials
use_secret_file("C:/Users/Colli/OneDrive/Everything/Documents/dcm-better-business/DCM_Emails/do_more_with_r.json")

```




```{r}


latest_msg <- "This is a test email using R. Hopefully it goes out"


my_email_message <- mime() %>%
  to("chenley4@gmu.edu") %>%
  from("collinhenley24@gmail.com") %>%
  subject(latest_msg)


send_message(my_email_message)




```












































